#:schema node_modules/wrangler/config-schema.json
name = "livetiming-mirror-api"
main = "src/index.js"
compatibility_date = "2024-07-18"
compatibility_flags = ["nodejs_compat"]

account_id = "b9261d7f75d36ec3c0ae559737628538"
workers_dev = true

[vars]
MAX_CACHE_AGE = "3600"

[[r2_buckets]]
binding = 'LIVETIMING_BUCKET'
bucket_name = 'fastf1-livetiming-mirror'
preview_bucket_name = 'fastf1-livetiming-mirror-dev'
